# Generated by Django 4.2 on 2023-04-11 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0003_rename_technician_id_wallet_technician'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='technician',
            new_name='technician_id',
        ),
    ]
