# Generated by Django 4.2 on 2023-04-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0004_rename_technician_wallet_technician_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechargehistory',
            name='payment_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
