# Generated by Django 4.2 on 2023-04-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0005_rechargehistory_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechargehistory',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
