# Generated by Django 4.2 on 2023-04-11 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0006_rechargehistory_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('technician_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homofix_app.technician')),
            ],
        ),
    ]
