# Generated by Django 4.2 on 2023-04-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0009_withdrawrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cash_on_service',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='online',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Inprocess', 'Inprocess'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('Reached', 'Reached'), ('Assign', 'Assign'), ('Proceed', 'Proceed')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='rebooking',
            name='status',
            field=models.CharField(choices=[('Assign', 'Assign'), ('Inprocess', 'Inprocess'), ('Completed', 'Completed')], default='Assign', max_length=20),
        ),
    ]
