# Generated by Django 4.2 on 2023-04-14 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0010_booking_cash_on_service_booking_online_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllTechnicianLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('technician_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homofix_app.technician')),
            ],
        ),
    ]
