# Generated by Django 4.2 on 2023-04-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0011_alltechnicianlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='bank_active',
            field=models.BooleanField(default=False),
        ),
    ]
