# Generated by Django 4.2 on 2023-04-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0012_kyc_bank_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
