# Generated by Django 4.2 on 2023-04-17 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0013_kyc_bank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='admin_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_admin_by', to='homofix_app.adminhod'),
        ),
    ]
