# Generated by Django 4.2 on 2023-04-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0014_booking_admin_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawrequest',
            name='status',
            field=models.CharField(choices=[('Process', 'Process'), ('Cancel', 'Cancel'), ('Accept', 'Accept')], default='Process', max_length=50),
        ),
    ]
