# Generated by Django 4.2 on 2023-05-01 07:13

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0019_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='Customer',
            new_name='customer_id',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='description',
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='technician_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homofix_app.technician'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='share',
            name='technician_share',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
