# Generated by Django 4.2 on 2023-05-01 07:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0020_rename_customer_feedback_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='hod_share',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
