# Generated by Django 4.2 on 2023-05-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0021_alter_share_hod_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingproduct',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
