# Generated by Django 4.2 on 2023-05-03 06:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0024_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='total_share',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
