# Generated by Django 4.2 on 2023-05-03 07:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0025_alter_wallet_total_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallethistory',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
