# Generated by Django 4.2 on 2023-05-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0026_alter_wallethistory_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('offer_pic', models.ImageField(upload_to='Offer')),
                ('url', models.URLField()),
            ],
        ),
    ]
