# Generated by Django 4.2 on 2023-05-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0027_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallethistory',
            name='type',
            field=models.CharField(choices=[('Add', 'Add'), ('deduction', 'Deduction')], max_length=10),
        ),
    ]
