# Generated by Django 4.2 on 2023-05-15 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0029_alter_wallethistory_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostViewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='MostViewed')),
                ('proudct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homofix_app.product')),
            ],
        ),
    ]
