# Generated by Django 4.2 on 2023-05-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0030_mostviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mostviewed',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='MostViewed'),
        ),
    ]
