# Generated by Django 4.2 on 2023-05-16 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0032_rename_proudct_mostviewed_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mostviewed',
            old_name='product_id',
            new_name='proudct',
        ),
    ]
