# Generated by Django 4.2 on 2023-05-16 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0033_rename_product_id_mostviewed_proudct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mostviewed',
            old_name='proudct',
            new_name='product_id',
        ),
    ]
