# Generated by Django 4.2 on 2023-05-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0034_rename_proudct_mostviewed_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='CatogryIcon'),
        ),
    ]
