# Generated by Django 4.2 on 2023-05-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0036_subcategory_subcategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='feedback',
        ),
        migrations.AddField(
            model_name='feedback',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
