# Generated by Django 4.2 on 2023-05-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0037_remove_feedback_feedback_feedback_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(max_length=50),
        ),
    ]
