# Generated by Django 4.2 on 2023-05-20 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0040_alter_feedback_description_alter_feedback_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
