# Generated by Django 4.2 on 2023-05-24 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0044_carrer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrer',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ApplicantCarrer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('resume', models.FileField(blank=True, null=True, upload_to='Job/Job Enquiry Form')),
                ('date', models.DateField(auto_now_add=True)),
                ('carrer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homofix_app.carrer')),
            ],
        ),
    ]
