# Generated by Django 4.2 on 2023-05-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0051_alter_bookingproduct_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='products',
            field=models.ManyToManyField(related_name='booking_products', through='homofix_app.BookingProduct', to='homofix_app.product'),
        ),
    ]
