# Generated by Django 4.2 on 2023-05-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0052_alter_booking_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobenquiry',
            name='expert_in',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
