# Generated by Django 4.2 on 2023-05-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0055_legalpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantcarrer',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
