# Generated by Django 4.2 on 2023-06-07 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0057_alter_applicantcarrer_email_alter_jobenquiry_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.BinaryField(blank=True, null=True)),
                ('invoice_name', models.CharField(max_length=100)),
                ('invoice_no', models.IntegerField()),
                ('booking_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homofix_app.booking')),
            ],
        ),
    ]
