# Generated by Django 4.2 on 2023-06-09 06:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0060_remove_invoice_invoice_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hodsharepercentage',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
