# Generated by Django 4.2 on 2023-06-12 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0068_booking_new_payment_booking_pay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='pay',
        ),
    ]
