# Generated by Django 4.2 on 2023-06-12 12:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0069_remove_booking_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pay',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
