# Generated by Django 4.2 on 2023-06-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0070_booking_pay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='pay',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
