# Generated by Django 4.2 on 2023-06-15 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0072_alter_payment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share',
            name='hod_share',
        ),
    ]
