# Generated by Django 4.2 on 2023-06-15 12:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0073_remove_share_hod_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='hod_share',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
