# Generated by Django 4.2 on 2023-06-15 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0074_share_hod_share'),
    ]

    operations = [
        migrations.RenameField(
            model_name='share',
            old_name='cmp_share',
            new_name='company_share',
        ),
        migrations.RemoveField(
            model_name='share',
            name='hod_share',
        ),
    ]
