# Generated by Django 4.2 on 2023-06-15 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0075_rename_cmp_share_share_company_share_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='share',
            old_name='company_share',
            new_name='hod_share',
        ),
    ]
