# Generated by Django 4.2 on 2023-06-15 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0079_settlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='technician_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homofix_app.technician'),
            preserve_default=False,
        ),
    ]
