# Generated by Django 4.2 on 2023-06-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0080_settlement_technician_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cash_on_service',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='online',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
