# Generated by Django 4.2 on 2023-06-22 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0081_alter_booking_cash_on_service_alter_booking_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='booking_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homofix_app.booking'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(choices=[('Online', 'Online'), ('Cash On Services', 'Cash On Services'), ('Qr', 'Qr')], default='Online', max_length=20),
        ),
    ]
