# Generated by Django 4.2 on 2023-06-24 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0083_alter_support_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mostviewed',
            name='product_id',
        ),
        migrations.AddField(
            model_name='mostviewed',
            name='subccategry_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homofix_app.subcategory'),
            preserve_default=False,
        ),
    ]
