# Generated by Django 4.2 on 2023-12-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0084_remove_mostviewed_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingproduct',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookingproduct',
            name='selling_price',
            field=models.IntegerField(default=0),
        ),
    ]
