# Generated by Django 4.2 on 2023-12-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0085_bookingproduct_price_bookingproduct_selling_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_customer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
