# Generated by Django 4.2 on 2023-12-24 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homofix_app', '0087_booking_area_booking_city_booking_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mostviewed',
            name='subccategry_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homofix_app.subcategory'),
        ),
    ]
